// GENERATED by scripts/build_hero.py — do not edit by hand.
// Positions are percentages of the scene box, measured off the backdrop
// plate, so one set of coordinates holds at every viewport width.
export type HeroItem = {
  id: string
  name: string
  price: string
  slug: string | null
  alt: string
  src: string
  hang: boolean
  left: number
  top: number
  w: number
  h: number
}

export const HERO_ITEMS: HeroItem[] = [
  {
    "id": "lotus-latkan",
    "name": "Lotus Latkan",
    "price": "DM for price",
    "slug": "lotus-latkan",
    "alt": "Lotus Latkan — handmade pink lotus and pearl garland, set of 2, 5 ft each",
    "src": "/assets/hero/lotus-latkan.webp",
    "hang": true,
    "left": 92.842,
    "top": 10.482,
    "w": 7.558,
    "h": 69.694
  },
  {
    "id": "door-latkan-orange",
    "name": "Orange Lotus Latkan",
    "price": "DM for price",
    "slug": null,
    "alt": "Orange Lotus Latkan — handmade orange velvet lotus blooms on a pearl chain, set of 2",
    "src": "/assets/hero/door-latkan-orange.webp",
    "hang": true,
    "left": 20.794,
    "top": 10.482,
    "w": 6.086,
    "h": 52.311
  },
  {
    "id": "decorative-latkan",
    "name": "Lotus Decorative Latkan",
    "price": "₹500 / pair",
    "slug": "lotus-decorative-latkan",
    "alt": "Lotus Decorative Latkan — red velvet roses on triple pearl strands, set of 2",
    "src": "/assets/hero/decorative-latkan.webp",
    "hang": true,
    "left": 35.193,
    "top": 10.482,
    "w": 6.577,
    "h": 39.355
  },
  {
    "id": "door-latkan-maroon",
    "name": "Maroon Lotus Latkan",
    "price": "DM for price",
    "slug": null,
    "alt": "Maroon Lotus Latkan — handmade deep-red velvet lotus blooms on a pearl chain, set of 2",
    "src": "/assets/hero/door-latkan-maroon.webp",
    "hang": true,
    "left": 49.609,
    "top": 10.482,
    "w": 5.723,
    "h": 50.586
  },
  {
    "id": "door-latkan-pink",
    "name": "Pink Lotus Latkan",
    "price": "DM for price",
    "slug": null,
    "alt": "Pink Lotus Latkan — handmade pink velvet lotus blooms on a pearl chain, set of 2",
    "src": "/assets/hero/door-latkan-pink.webp",
    "hang": true,
    "left": 78.443,
    "top": 10.482,
    "w": 5.214,
    "h": 53.971
  },
  {
    "id": "purple-latkan",
    "name": "Purple Lotus Latkan",
    "price": "₹800 / pair",
    "slug": "purple-lotus-latkan",
    "alt": "Purple Lotus Latkan — handmade purple lotus and pearl garland, set of 2, 3 ft each",
    "src": "/assets/hero/purple-latkan.webp",
    "hang": true,
    "left": 64.026,
    "top": 10.482,
    "w": 5.487,
    "h": 49.577
  },
  {
    "id": "bouquet-pink",
    "name": "Pink Bouquet",
    "price": "DM for price",
    "slug": "bouquets",
    "alt": "Everlasting Bouquet — handmade pink lilies and tulips in a cream wrap",
    "src": "/assets/hero/bouquet-pink.webp",
    "hang": false,
    "left": 66.506,
    "top": 50.553,
    "w": 13.717,
    "h": 33.952
  },
  {
    "id": "bouquet",
    "name": "Purple Bouquet",
    "price": "DM for price",
    "slug": "bouquets",
    "alt": "Everlasting Bouquet — handmade lavender lilies and purple lavender sprigs in a lilac wrap",
    "src": "/assets/hero/bouquet.webp",
    "hang": false,
    "left": 39.617,
    "top": 51.465,
    "w": 13.463,
    "h": 33.952
  },
  {
    "id": "mini-frame",
    "name": "Mini Frame",
    "price": "₹400–500",
    "slug": "mini-frame",
    "alt": "Mini Frame — a small handmade craft-wire bloom in a keepsake frame",
    "src": "/assets/hero/mini-frame.webp",
    "hang": false,
    "left": 91.297,
    "top": 69.076,
    "w": 10.32,
    "h": 22.07
  },
  {
    "id": "photo-frame",
    "name": "Signature Frame",
    "price": "₹900–1,200",
    "slug": "signature-frame",
    "alt": "Signature Frame — your photo framed inside hand-shaped craft-wire flowers",
    "src": "/assets/hero/photo-frame.webp",
    "hang": false,
    "left": 25.445,
    "top": 59.798,
    "w": 17.278,
    "h": 32.324
  },
  {
    "id": "asaan",
    "name": "Lotus Asaan",
    "price": "₹350",
    "slug": "lotus-asaan",
    "alt": "Lotus Asaan — handmade pink lotus seat on green leaves, for your Ganpati idol",
    "src": "/assets/hero/asaan.webp",
    "hang": false,
    "left": 53.606,
    "top": 73.112,
    "w": 13.463,
    "h": 19.987
  },
  {
    "id": "bouquet-blush",
    "name": "Blush Bouquet",
    "price": "DM for price",
    "slug": "bouquets",
    "alt": "Everlasting Bouquet — a handmade pink lily and white daisies in a blush wrap",
    "src": "/assets/hero/bouquet-blush.webp",
    "hang": false,
    "left": 78.125,
    "top": 59.277,
    "w": 11.555,
    "h": 33.952
  }
]
