// GENERATED by scripts/build_hero.py — do not edit by hand.
// Positions are percentages of the scene box, measured off the backdrop
// plate, so one set of coordinates holds at every viewport width.
export type HeroItem = {
  id: string
  name: string
  price: string
  slug: string | null
  alt: string
  src: string
  hang: boolean
  left: number
  top: number
  w: number
  h: number
}

export const HERO_ITEMS: HeroItem[] = [
  {
    "id": "lotus-latkan",
    "name": "Lotus Latkan",
    "price": "DM for price",
    "slug": "lotus-latkan",
    "alt": "Lotus Latkan — handmade pink lotus and pearl garland, set of 2, 5 ft each",
    "src": "/assets/hero/lotus-latkan.webp",
    "hang": true,
    "left": 92.842,
    "top": 10.482,
    "w": 7.558,
    "h": 69.694
  },
  {
    "id": "door-latkan-coral",
    "name": "Door Side Latkan",
    "price": "DM for price",
    "slug": null,
    "alt": "Door Side Latkan — handmade coral lotus latkan on a pearl chain",
    "src": "/assets/hero/door-latkan-coral.webp",
    "hang": true,
    "left": 20.794,
    "top": 10.482,
    "w": 5.65,
    "h": 33.366
  },
  {
    "id": "decorative-latkan",
    "name": "Lotus Decorative Latkan",
    "price": "₹500 / pair",
    "slug": "lotus-decorative-latkan",
    "alt": "Lotus Decorative Latkan — red velvet roses on triple pearl strands, set of 2",
    "src": "/assets/hero/decorative-latkan.webp",
    "hang": true,
    "left": 35.193,
    "top": 10.482,
    "w": 6.577,
    "h": 39.355
  },
  {
    "id": "flower-mala",
    "name": "Artificial Flower Mala",
    "price": "₹150–200",
    "slug": "flower-mala",
    "alt": "Artificial Flower Mala — handmade velvet flower and pearl garland",
    "src": "/assets/hero/flower-mala.webp",
    "hang": true,
    "left": 49.6,
    "top": 10.482,
    "w": 7.994,
    "h": 32.324
  },
  {
    "id": "door-latkan-pink",
    "name": "Door Side Latkan",
    "price": "DM for price",
    "slug": null,
    "alt": "Door Side Latkan — handmade pink and gold lotus latkan with pearls",
    "src": "/assets/hero/door-latkan-pink.webp",
    "hang": true,
    "left": 78.443,
    "top": 10.482,
    "w": 5.614,
    "h": 33.366
  },
  {
    "id": "purple-latkan",
    "name": "Purple Lotus Latkan",
    "price": "₹800 / pair",
    "slug": "purple-lotus-latkan",
    "alt": "Purple Lotus Latkan — handmade purple lotus and pearl garland, set of 2, 3 ft each",
    "src": "/assets/hero/purple-latkan.webp",
    "hang": true,
    "left": 64.026,
    "top": 10.482,
    "w": 5.523,
    "h": 50.618
  },
  {
    "id": "photo-frame",
    "name": "Signature Frame",
    "price": "₹900–1,200",
    "slug": "signature-frame",
    "alt": "Signature Frame — your photo framed inside hand-shaped craft-wire flowers",
    "src": "/assets/hero/photo-frame.webp",
    "hang": false,
    "left": 25.445,
    "top": 59.798,
    "w": 17.278,
    "h": 32.324
  },
  {
    "id": "bouquet",
    "name": "Bouquets",
    "price": "DM for price",
    "slug": "bouquets",
    "alt": "Everlasting Bouquet — handmade purple craft-wire flowers, wrapped and ribboned",
    "src": "/assets/hero/bouquet.webp",
    "hang": false,
    "left": 42.197,
    "top": 48.503,
    "w": 15.534,
    "h": 36.914
  },
  {
    "id": "asaan",
    "name": "Lotus Asaan",
    "price": "₹350",
    "slug": "lotus-asaan",
    "alt": "Lotus Asaan — handmade pink lotus seat on green leaves, for your Ganpati idol",
    "src": "/assets/hero/asaan.webp",
    "hang": false,
    "left": 65.779,
    "top": 65.43,
    "w": 13.463,
    "h": 19.987
  },
  {
    "id": "mini-frame",
    "name": "Mini Frame",
    "price": "₹400–500",
    "slug": "mini-frame",
    "alt": "Mini Frame — a small handmade craft-wire bloom in a keepsake frame",
    "src": "/assets/hero/mini-frame.webp",
    "hang": false,
    "left": 79.215,
    "top": 62.305,
    "w": 10.32,
    "h": 22.07
  }
]
