'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { HERO_ITEMS, type HeroItem } from '@/lib/heroScene'
import { useInstagramLink } from './IgLink'

/**
 * The interactive hero scene: one backdrop plate with twelve real products
 * composited over it, each a link.
 *
 * Geometry (every position, size and the scene's aspect ratio) is generated by
 * scripts/build_hero.py and imported from lib/heroScene.ts — it is measured off
 * the backdrop plate itself, so nothing here is hand-tuned and the two can't
 * drift apart. Re-run that script after changing any product; don't nudge the
 * numbers here.
 *
 * The lighting, cast shadows and true-scale sizing are baked into the webp
 * files by that same script. What lives here is only what has to move.
 */

/**
 * A pendulum's period goes with the square root of its length, so a 5ft garland
 * genuinely swings slower than a 1.5ft one. Deriving the duration from each
 * piece's own height is what stops the rod reading as a row of identical
 * bobbing stickers — which is exactly how the old scene failed. `h` is a
 * percentage of scene height; the constants just put the result in a range that
 * reads as "barely moving air" rather than "windy".
 */
function swingSeconds(item: HeroItem) {
  return 4.6 + Math.sqrt(item.h) * 0.72
}

/** How long each piece holds the spotlight when the scene plays itself. */
const CYCLE_MS = 2600

export default function HeroScene() {
  const [active, setActive] = useState<string | null>(null)
  /* A hero tile for a product with no page of its own opens Instagram instead,
     so it needs the same app hand-off as every other DM link on the site. */
  const ig = useInstagramLink()
  /** True once a real person has hovered or tapped — stops the auto-cycle for good. */
  const [taken, setTaken] = useState(false)
  const sceneRef = useRef<HTMLDivElement>(null)

  const take = useCallback((id: string | null) => {
    setTaken(true)
    setActive(id)
  }, [])

  /**
   * Touch devices have no hover, so nothing would ever reveal that the scene is
   * interactive. Instead it plays itself — each piece lifts in turn — until the
   * visitor taps one, at which point they take over and the cycle stops.
   */
  useEffect(() => {
    if (taken || typeof window === 'undefined') return
    if (!window.matchMedia('(hover: none)').matches) return
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return

    let i = 0
    setActive(HERO_ITEMS[0].id)
    const t = setInterval(() => {
      i = (i + 1) % HERO_ITEMS.length
      setActive(HERO_ITEMS[i].id)
    }, CYCLE_MS)
    return () => clearInterval(t)
  }, [taken])

  /**
   * Depth parallax. The old scene rotated each flat cut-out in 3D on pointer
   * move, which is the single most reliable way to prove to the eye that a
   * thing IS flat. Shifting the layers against each other instead reads as
   * depth precisely because nothing rotates: the products sit in front of the
   * wall, so they track the pointer slightly more than the plate does.
   */
  useEffect(() => {
    const el = sceneRef.current
    if (!el || typeof window === 'undefined') return
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return

    let frame = 0
    const onMove = (e: PointerEvent) => {
      if (frame) return
      frame = requestAnimationFrame(() => {
        frame = 0
        const r = el.getBoundingClientRect()
        const px = (e.clientX - (r.left + r.width / 2)) / (r.width / 2)
        const py = (e.clientY - (r.top + r.height / 2)) / (r.height / 2)
        el.style.setProperty('--hs-px', String(Math.max(-1, Math.min(1, px))))
        el.style.setProperty('--hs-py', String(Math.max(-1, Math.min(1, py))))
      })
    }
    const onLeave = () => {
      el.style.setProperty('--hs-px', '0')
      el.style.setProperty('--hs-py', '0')
    }
    el.addEventListener('pointermove', onMove)
    el.addEventListener('pointerleave', onLeave)
    return () => {
      el.removeEventListener('pointermove', onMove)
      el.removeEventListener('pointerleave', onLeave)
      if (frame) cancelAnimationFrame(frame)
    }
  }, [])

  return (
    <div className="hs-stage">
      <div
        className={`hs-scene${active ? ' is-spotlit' : ''}`}
        ref={sceneRef}
        onPointerLeave={() => setActive(null)}
      >
        {/* Real <img>, not a CSS background, so the preload scanner finds the
            LCP image immediately. Phones crop the scene rather than shrinking
            it, so they still need more plate than their own width — but not the
            full 2752px. */}
        <picture>
          <source media="(max-width: 760px)" srcSet="/assets/hero/backdrop-1400.webp" />
          <img
            className="hs-plate"
            src="/assets/hero/backdrop.webp"
            alt=""
            width={2064}
            height={1152}
            fetchPriority="high"
            decoding="async"
          />
        </picture>

        {HERO_ITEMS.map((it) => {
          const state = active === it.id ? ' is-active' : active ? ' is-dimmed' : ''
          return (
            <a
              key={it.id}
              className={`hs-item hs-item--${it.hang ? 'hang' : 'rest'}${state}`}
              {...(it.slug ? { href: `/products/${it.slug}` } : ig)}
              aria-label={`${it.name} — ${it.price}`}
              style={{
                left: `${it.left}%`,
                top: `${it.top}%`,
                width: `${it.w}%`,
                height: `${it.h}%`,
                ['--swing' as string]: `${swingSeconds(it).toFixed(2)}s`,
                // Negative delay starts each piece mid-swing, so they never
                // move in lockstep the way a shared animation would.
                ['--swing-delay' as string]: `-${(it.left % 3.7).toFixed(2)}s`,
              }}
              onPointerEnter={() => take(it.id)}
              onFocus={() => take(it.id)}
              onBlur={() => setActive(null)}
            >
              <span className="hs-swing">
                {/* .hs-swing owns `transform` for the pendulum keyframes, so the
                    hover pop needs its own layer or the two overwrite each other
                    and the piece stops moving the moment you touch it. */}
                <span className="hs-pop">
                  <img src={it.src} alt={it.alt} decoding="async" />
                </span>
              </span>
              <span className="hs-label" aria-hidden>
                <span className="hs-label-name">{it.name}</span>
                <span className="hs-label-price">{it.price}</span>
              </span>
            </a>
          )
        })}
      </div>
    </div>
  )
}
